FROM cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1

COPY e2e/ /opt/app/e2e/
RUN apt update && cd /opt/app/e2e
WORKDIR /opt/app/e2e
RUN npm install && npx cypress install
